# Generated by Django 5.1.4 on 2024-12-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0002_seller_invoice_invoiceproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
