# Generated by Django 5.1.4 on 2024-12-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0004_invoice_total_price_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
