# Generated by Django 5.1.4 on 2024-12-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0005_remove_invoice_total_price_invoice_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
